/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const FlashcardLazyImport = createFileRoute('/flashcard')()
const ChatLazyImport = createFileRoute('/chat')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const FlashcardLazyRoute = FlashcardLazyImport.update({
  path: '/flashcard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/flashcard.lazy').then((d) => d.Route))

const ChatLazyRoute = ChatLazyImport.update({
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/chat.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      preLoaderRoute: typeof ChatLazyImport
      parentRoute: typeof rootRoute
    }
    '/flashcard': {
      preLoaderRoute: typeof FlashcardLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ChatLazyRoute,
  FlashcardLazyRoute,
])

/* prettier-ignore-end */
